### ISSUE TITLE
Spelling error Live website

### ISSUE THREAD

**Issue by andrewk1** [TreeHacks/live-schedule#35]
Line 58 of `content.json` should be  "name": "Open Souce Initiative",

![image](https://user-images.githubusercontent.com/20730635/52746896-76ba5180-2f97-11e9-808a-dc4fb7f3f90f.png)

**Comment by andrewk1** [comment]
Looks like both "Source" and "Initiative" were misspelled.

**Comment by oliviabrown9** [comment]
Closed with d875258ecf5ed2faec8202605bee1eebbd019ed6
